Milestone five
geraldgsh/react-calculator pull request #7
Opened 2020-04-10 22:36 UTC by geraldgsh

1. Implement the handleClick function in app.js
2. Add buttonName as an argument to handleClick function in app.js
3. Pass the total or next value to Display to display the current result in app.js
4. Pass handleClick as a clickHandler property to ButtonPanel in app.js
5. Implement the handleClick function in buttonPanel.js
6. Add buttonName as an argument which returns clickHandler from props in buttonPanel.js
7. Pass the clickHandler property to each button in buttonPanel.js
8. Implement the handleClick function in button.js
9. Add buttonName as an argument which returns clickHandler from props in button.js
10. Implement onClick event to attach the handleClick event to the button in button.js
11. Add display conditions in calculate.js
12. Stringify operands in operate.js

2020-04-11 15:41 UTC, shloch requested changes
## perfect job @geraldgsh 

![Screen Shot 2020-04-11 at 4 45 06 PM](https://user-images.githubusercontent.com/40712459/79048206-4a3dac00-7c13-11ea-844d-7ebfb2c497b0.png)
### one more thing below, before thumbs up ......let's do this !!

2020-04-11 15:41 UTC, shloch commented on src/logic/operate.js
> +      return one.div(two).toString();
manage division by error.........You can display an error on screen or something (`'INFNITY`)....just handle it
![Screen Shot 2020-04-11 at 4 41 34 PM](https://user-images.githubusercontent.com/40712459/79048144-e4e9bb00-7c12-11ea-93cd-c1ff5042aace.png)

2020-04-12 18:50 UTC, geraldgsh commented
Thanks @shloch, i'll make amendments accordingly.

2020-04-13 09:31 UTC, shloch approved these changes
### we're good to go...............on to next project

![accomplished](https://user-images.githubusercontent.com/40712459/79110247-ed0c3c80-7d71-11ea-93c2-cb64aeae30e2.jpg)

2020-04-13 10:03 UTC, merged